config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  devise_for :librarians
  resources :clients
  resources :books
  resources :categories
  resources :authors
  root to: "reservations#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  validates :name, presence: :true
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<div class="box box-primary">
    
    <!-- /.box-header -->
    <!-- form start -->
    <%= form_with(model: author, local: true) do |form| %>
      <div class="box-body">
        <% if author.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>
            <ul>
            <% author.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>


        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control", placeholder: "Name" %>
        </div>

        <div class="actions">
          <%= form.submit 'Create Author', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author, class: "btn btn-info", style: "color: white;" %> |
<%= link_to 'Back', authors_path, class: "btn btn-default" %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Authors</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <table class="table table-bordered">
      <tbody><tr>
        <th>Name</th>
      </tr>
      <% @authors.each do |author| %>
        <tr>
          <td><%= author.name %></td>
          <td><%= link_to 'Show', author %></td>
          <td><%= link_to 'Edit', edit_author_path(author) %></td>
          <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <%end%>
    </tbody></table>
  </div>
  <!-- /.box-body -->
</div>
<%= link_to 'New Author', new_author_path, class: "btn btn-primary", style: "color: white;" %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path, class: "btn btn-default" %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>
<section class="invoice">
  <div class="row invoice-info">
    <!-- /.col -->
    <div class="col-sm-4 invoice-col">
      <b>Name:</b> <%= @author.name %><br>
    </div>
    <!-- /.col -->
  </div>
</section>
<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>